Get http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjcxNDUyMjI1fQ.KtYF4OMkGIBZ9qZgMSsahZ32GPhphrf5SKL5VaI8Z2g

####
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

####
POST http://localhost:3000/login
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

####
Get http://localhost:3000/tweets/11/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjcxNDUyMjI1fQ.KtYF4OMkGIBZ9qZgMSsahZ32GPhphrf5SKL5VaI8Z2g


####
Get http://localhost:3000/tweets/4/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjcxNDUyMjI1fQ.KtYF4OMkGIBZ9qZgMSsahZ32GPhphrf5SKL5VaI8Z2g



####
Get http://localhost:3000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjcxNDUyMjI1fQ.KtYF4OMkGIBZ9qZgMSsahZ32GPhphrf5SKL5VaI8Z2g

####
Get http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjcxNDUyMjI1fQ.KtYF4OMkGIBZ9qZgMSsahZ32GPhphrf5SKL5VaI8Z2g